POST https://nodejscrud-a70b.onrender.com/users
Content-Type: application/json
Accept-Language: pt-br

{
    "name": "Carla Mendes",
    "email": "carla.mendes@example.com",
    "password": "5Tg#jKdP",
    "cell": "85985459814",
    "category": "Expedição",
    "route": "Crato"
}
###

GET https://nodejscrud-a70b.onrender.com/users
Accept-Language: pt-br

###
PUT https://nodejscrud-a70b.onrender.com/users/10
Content-Type: application/json
Accept-Language: pt-br

{
    "name": "Carla Fernandes",
    "email": "carla.fernandes@glassmaxi.com.br",
    "password": "9zG&r@mP",
    "cell": "85985459814",
    "category": "Expedição",
    "route": "Sobral"
}

###
DELETE https://nodejscrud-a70b.onrender.com/users/12
Accept-Language: pt-br

